apiVersion: v1
kind: Service
metadata:
  name: miwebnginx #Ojo este nombre lo colocamos en el index.msj (linea 16) de nuestra App, tienen que coincidir
spec:
  type: ClusterIP
  selector:
    app: portalnginx
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miwebnginx
  namespace: default
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: portalnginx
  template:
    metadata:
      labels:
        app: portalnginx
    spec:
      containers:
        - name: contenedor-portalnginx
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
